import type { Metadata } from "next";

import Header from "./component/Header";
import Footer from "./component/footer";




export const metadata: Metadata = {
  title: "Addis Eats",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      
    > 
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}